name: golangci-lint

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          # NOTE: Keep this in sync with the version from go.mod
          go-version: '1.21.x'
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # NOTE: Keep this in sync with the version from .golangci.yml
          version: 'v1.52.2'
